OK_FORMAT = True

test = {   'name': 'Linear Layer',
    'points': 5,
    'suites': [   {   'cases': [   {   'code': '>>> list(Linear(25, 28)(torch.zeros((17, 25))).shape) == [17, 28]\nTrue',
                                       'failure_message': 'Shape Test Failed',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0,
                                       'success_message': 'Shape Test Passed'},
                                   {   'code': '>>> type(Linear(13, 15)(torch.zeros((6, 13)))) in [torch.Tensor, torch.nn.Parameter]\nTrue',
                                       'failure_message': 'Type Test Failed',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0,
                                       'success_message': 'Type Test Passed'},
                                   {   'code': ">>> hasattr(Linear(2, 2), 'w') and hasattr(Linear(2, 2), 'b')\nTrue",
                                       'failure_message': 'Param Name Test Failed',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0,
                                       'success_message': 'Param Name Test Passed'},
                                   {   'code': '>>> layer = Linear(13, 24)\n>>> list(layer.w.shape) in [[13, 24], [24, 13]] and list(layer.b.shape) == [24]\nTrue',
                                       'failure_message': 'Param Shape Test Failed',
                                       'hidden': False,
                                       'locked': False,
                                       'points': 0,
                                       'success_message': 'Param Shape Test Passed'}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
