apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aki-detection-state
  namespace: hoofdvaart
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aki-detection
  namespace: hoofdvaart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aki-detection
  template:
    metadata:
      labels:
        app: aki-detection
    spec:
      containers:
      - name: aki-detection
        image: imperialswemlsspring2025.azurecr.io/coursework4-hoofdvaart
        # Replace this with the correct command for your solution
        #command: ["/coursework3/client.py"]
        #command: ["/client.py"]
        command: ["/simulator/bin/python3"]
        args:
        # Replace this with however you tell your solution where to find the
        # initial history file. /data is mounted below.
        #- "--history=/data/history.csv"
        - "/simulator/client.py"
        - "--history=/data/history.csv"
        env:
        - name: MLLP_ADDRESS
          value: hoofdvaart-simulator.coursework4:8440
        - name: PAGER_ADDRESS
          value: hoofdvaart-simulator.coursework4:8441
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
          - mountPath: "/data"
            name: hospital-history
            readOnly: true
          - mountPath: "/state"
            name: aki-detection-state
        resources:
          requests:
            memory: 800Mi
            cpu: 0.9
      initContainers:
      - name: copy-hospital-history
        image: imperialswemlsspring2025.azurecr.io/coursework4-history
        volumeMounts:
          - mountPath: "/data"
            name: hospital-history
        resources:
          requests:
            memory: 200Mi
            cpu: 0.1
      volumes:
      - name: hospital-history
        emptyDir:
          sizeLimit: 50Mi
      - name: aki-detection-state
        persistentVolumeClaim:
          claimName: aki-detection-state